#spring
server:
  port: ${port:8085}
  forward-headers-strategy: framework



#mongodb configuration
spring:
  application:
    name: estock-market-api
  data:
    mongodb:
      database: a_esm_db
      uri: mongodb://rajeshb7631:vidwan9652@ac-d1mo7dp-shard-00-00.wzhd6bc.mongodb.net:27017,ac-d1mo7dp-shard-00-01.wzhd6bc.mongodb.net:27017,ac-d1mo7dp-shard-00-02.wzhd6bc.mongodb.net:27017/?ssl=true&replicaSet=atlas-s17ie3-shard-0&authSource=admin&retryWrites=true&w=majority
# security
security:
  oauth2:
    resource:
      jwt:
        key-value: eStockMarketSigningKey


estock:
  market:
    tokenURL: http://localhost:8084/oauth/token
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    config-url: /estock-market-api/openapi/swagger-config
    url: /estock-market-api/openapi
    path: /estock-market-api/openapi/index.html
  api-docs:
    path: /estock-market-api/openapi

