eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  application:
    name: ESTOCK-MARKET-GATEWAY
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  cloud:
    gateway:
      httpclient:
        ssl:
          handshake-timeout-millis: 10000
          close-notify-flush-timeout-millis: 3000
          close-notify-read-timeout-millis: 0
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: "*"
      routes:
        - id: User-Query-Services
          uri: http://44.211.37.102:8082/
#          uri: http://localhost:8082/
          predicates:
            - Path=/api/v1.0/user/**, /api/v1.0/user/*/**,/estock-market-user-api/*/**

        - id: Company-Query-Services
          uri: http://54.236.42.99:8085/
#          uri: http://localhost:8085/
          predicates:
            - Path=/api/v1.0/market/company/**,/api/v1.0/market/company/*/**,/api/v1.0/market/stock/*/**,/estock-market-api/*/**

        - id: User-Authentication-Service
          uri: http://34.205.2.168:8084/
#          uri: http://localhost:8084/
          predicates:
            - Path=/api/v1.0/**,/api/v1.0/*/**,/authentication-api/*/**,/oauth/**
